import time
print("==================")
print("Created By Rovanio")
print("==================")
time.sleep(3)
print("\n" * 50)
print("=====================")
print("Welcome to Calculator")
print("=====================")
num1 = input("Enter the first number: ")
num2 = input("Enter the second number: ")
choose = input("Enter / or * or + or -: ")
if choose == "/":
  result_/ = float(num1)/float(num2)
  print(result_/)
  time.sleep(3)
  print("")
if choose == "*":
  result_* = float(num1)*float(num2)
  print(result_*)
  time.sleep(3)
  print("")
if choose == "+":
  result_+ = float(num1)*float(num2)
  print(result_+)
  time.sleep(3)
  print("")
if choose == "-"
  result_- = float(num1)-float(num2)
  print(result_-)
  time.sleep(3)
  print("")
